// Modifidied from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/carbon__icons-react for @carbon/icons-react v11

declare module '@carbon/react/icons' {
    export interface CarbonIconProps
        extends Omit<React.SVGProps<React.ReactSVGElement>, "ref" | "tabIndex" | "aria-hidden"> {
        "aria-hidden"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        height?: number | undefined;
        preserveAspectRatio?: string | undefined;
        tabIndex?: string | undefined;
        title?: string | undefined;
        viewBox?: string | undefined;
        width?: number | undefined;
        xmlns?: string | undefined;
    }
    
    export type CarbonIconType = React.ForwardRefExoticComponent<CarbonIconProps & React.RefAttributes<SVGSVGElement>>;
    
    export interface CarbonIconNextProps
        extends Omit<React.SVGProps<React.ReactSVGElement>, "ref" | "tabIndex" | "aria-hidden"> {
        /** @default "http://www.w3.org/2000/svg" */
        xmlns?: string | undefined;
    
        /** @default "xMidYMid meet" */
        preserveAspectRatio?: string | undefined;
    
        /**
         * @default 32
         * size is set to `16` if value is `glyph` or `glyphpx`
         */
    
        size?: 16 | 20 | 24 | 32 | "16" | "20" | "24" | "32" | "glyph" | "glyphpx" | undefined;
    
        width?: number | string | undefined;
        height?: number | string | undefined;
        "aria-hidden"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        tabIndex?: string | undefined;
        title?: string | undefined;
        viewBox?: string | undefined;
    }
    
    export type CarbonIconNextType = React.ForwardRefExoticComponent<
        CarbonIconNextProps & React.RefAttributes<SVGSVGElement>
    >;
    
    export const Accessibility: CarbonIconNextType
    export const AccessibilityAlt: CarbonIconNextType
    export const AccessibilityColor: CarbonIconNextType
    export const AccessibilityColorFilled: CarbonIconNextType
    export const Account: CarbonIconNextType
    export const AccumulationIce: CarbonIconNextType
    export const AccumulationPrecipitation: CarbonIconNextType
    export const AccumulationRain: CarbonIconNextType
    export const AccumulationSnow: CarbonIconNextType
    export const Activity: CarbonIconNextType
    export const Add: CarbonIconNextType
    export const AddAlt: CarbonIconNextType
    export const AddComment: CarbonIconNextType
    export const AddFilled: CarbonIconNextType
    export const AgricultureAnalytics: CarbonIconNextType
    export const AirlineDigitalGate: CarbonIconNextType
    export const AirlineManageGates: CarbonIconNextType
    export const AirlinePassengerCare: CarbonIconNextType
    export const AirlineRapidBoard: CarbonIconNextType
    export const Airplay: CarbonIconNextType
    export const AirplayFilled: CarbonIconNextType
    export const AirportLocation: CarbonIconNextType
    export const Airport_01: CarbonIconNextType
    export const Airport_02: CarbonIconNextType
    export const Alarm: CarbonIconNextType
    export const AlarmAdd: CarbonIconNextType
    export const AlarmSubtract: CarbonIconNextType
    export const AlignBoxBottomCenter: CarbonIconNextType
    export const AlignBoxBottomLeft: CarbonIconNextType
    export const AlignBoxBottomRight: CarbonIconNextType
    export const AlignBoxMiddleCenter: CarbonIconNextType
    export const AlignBoxMiddleLeft: CarbonIconNextType
    export const AlignBoxMiddleRight: CarbonIconNextType
    export const AlignBoxTopCenter: CarbonIconNextType
    export const AlignBoxTopLeft: CarbonIconNextType
    export const AlignBoxTopRight: CarbonIconNextType
    export const AlignHorizontalCenter: CarbonIconNextType
    export const AlignHorizontalLeft: CarbonIconNextType
    export const AlignHorizontalRight: CarbonIconNextType
    export const AlignVerticalBottom: CarbonIconNextType
    export const AlignVerticalCenter: CarbonIconNextType
    export const AlignVerticalTop: CarbonIconNextType
    export const Analytics: CarbonIconNextType
    export const AnalyticsCustom: CarbonIconNextType
    export const AnalyticsReference: CarbonIconNextType
    export const Aperture: CarbonIconNextType
    export const Api: CarbonIconNextType
    export const Api_1: CarbonIconNextType
    export const App: CarbonIconNextType
    export const AppConnectivity: CarbonIconNextType
    export const Apple: CarbonIconNextType
    export const Application: CarbonIconNextType
    export const ApplicationMobile: CarbonIconNextType
    export const ApplicationVirtual: CarbonIconNextType
    export const ApplicationWeb: CarbonIconNextType
    export const Apps: CarbonIconNextType
    export const Archive: CarbonIconNextType
    export const Area: CarbonIconNextType
    export const AreaCustom: CarbonIconNextType
    export const Arrival: CarbonIconNextType
    export const ArrowDown: CarbonIconNextType
    export const ArrowDownLeft: CarbonIconNextType
    export const ArrowDownRight: CarbonIconNextType
    export const ArrowLeft: CarbonIconNextType
    export const ArrowRight: CarbonIconNextType
    export const ArrowShiftDown: CarbonIconNextType
    export const ArrowUp: CarbonIconNextType
    export const ArrowUpLeft: CarbonIconNextType
    export const ArrowUpRight: CarbonIconNextType
    export const ArrowsHorizontal: CarbonIconNextType
    export const ArrowsVertical: CarbonIconNextType
    export const Asleep: CarbonIconNextType
    export const AsleepFilled: CarbonIconNextType
    export const Assembly: CarbonIconNextType
    export const AssemblyCluster: CarbonIconNextType
    export const AssemblyReference: CarbonIconNextType
    export const Asset: CarbonIconNextType
    export const AssetConfirm: CarbonIconNextType
    export const AssetDigitalTwin: CarbonIconNextType
    export const AssetView: CarbonIconNextType
    export const Asterisk: CarbonIconNextType
    export const At: CarbonIconNextType
    export const Attachment: CarbonIconNextType
    export const AudioConsole: CarbonIconNextType
    export const AugmentedReality: CarbonIconNextType
    export const Automatic: CarbonIconNextType
    export const Autoscaling: CarbonIconNextType
    export const Awake: CarbonIconNextType
    export const Badge: CarbonIconNextType
    export const BaggageClaim: CarbonIconNextType
    export const Bar: CarbonIconNextType
    export const Barcode: CarbonIconNextType
    export const BareMetalServer: CarbonIconNextType
    export const BareMetalServer_01: CarbonIconNextType
    export const BareMetalServer_02: CarbonIconNextType
    export const Basketball: CarbonIconNextType
    export const BastionHost: CarbonIconNextType
    export const Bat: CarbonIconNextType
    export const BatteryCharging: CarbonIconNextType
    export const BatteryEmpty: CarbonIconNextType
    export const BatteryFull: CarbonIconNextType
    export const BatteryHalf: CarbonIconNextType
    export const BatteryLow: CarbonIconNextType
    export const BatteryQuarter: CarbonIconNextType
    export const Bee: CarbonIconNextType
    export const BeeBat: CarbonIconNextType
    export const Beta: CarbonIconNextType
    export const Bicycle: CarbonIconNextType
    export const Binoculars: CarbonIconNextType
    export const BlockStorage: CarbonIconNextType
    export const BlockStorageAlt: CarbonIconNextType
    export const Blockchain: CarbonIconNextType
    export const Blog: CarbonIconNextType
    export const Bluetooth: CarbonIconNextType
    export const BluetoothOff: CarbonIconNextType
    export const Book: CarbonIconNextType
    export const Bookmark: CarbonIconNextType
    export const BookmarkAdd: CarbonIconNextType
    export const BookmarkFilled: CarbonIconNextType
    export const Boolean: CarbonIconNextType
    export const Boot: CarbonIconNextType
    export const BorderBottom: CarbonIconNextType
    export const BorderFull: CarbonIconNextType
    export const BorderLeft: CarbonIconNextType
    export const BorderNone: CarbonIconNextType
    export const BorderRight: CarbonIconNextType
    export const BorderTop: CarbonIconNextType
    export const Bot: CarbonIconNextType
    export const Box: CarbonIconNextType
    export const BoxExtraLarge: CarbonIconNextType
    export const BoxLarge: CarbonIconNextType
    export const BoxMedium: CarbonIconNextType
    export const BoxPlot: CarbonIconNextType
    export const BoxSmall: CarbonIconNextType
    export const Branch: CarbonIconNextType
    export const BreakingChange: CarbonIconNextType
    export const BrightnessContrast: CarbonIconNextType
    export const BringForward: CarbonIconNextType
    export const BringToFront: CarbonIconNextType
    export const Building: CarbonIconNextType
    export const BuildingInsights_1: CarbonIconNextType
    export const BuildingInsights_2: CarbonIconNextType
    export const BuildingInsights_3: CarbonIconNextType
    export const Bullhorn: CarbonIconNextType
    export const Buoy: CarbonIconNextType
    export const Bus: CarbonIconNextType
    export const ButtonCentered: CarbonIconNextType
    export const ButtonFlushLeft: CarbonIconNextType
    export const CabinCare: CarbonIconNextType
    export const CabinCareAlert: CarbonIconNextType
    export const CabinCareAlt: CarbonIconNextType
    export const Cad: CarbonIconNextType
    export const Cafe: CarbonIconNextType
    export const Calculation: CarbonIconNextType
    export const CalculationAlt: CarbonIconNextType
    export const Calculator: CarbonIconNextType
    export const CalculatorCheck: CarbonIconNextType
    export const Calendar: CarbonIconNextType
    export const CalendarAdd: CarbonIconNextType
    export const CalendarAddAlt: CarbonIconNextType
    export const CalendarHeatMap: CarbonIconNextType
    export const CalendarSettings: CarbonIconNextType
    export const CalendarTools: CarbonIconNextType
    export const Calibrate: CarbonIconNextType
    export const Camera: CarbonIconNextType
    export const CameraAction: CarbonIconNextType
    export const Campsite: CarbonIconNextType
    export const Car: CarbonIconNextType
    export const CarFront: CarbonIconNextType
    export const Carbon: CarbonIconNextType
    export const CarbonAccounting: CarbonIconNextType
    export const CarbonForIbmDotcom: CarbonIconNextType
    export const CarbonForIbmProduct: CarbonIconNextType
    export const CaretDown: CarbonIconNextType
    export const CaretLeft: CarbonIconNextType
    export const CaretRight: CarbonIconNextType
    export const CaretSort: CarbonIconNextType
    export const CaretSortDown: CarbonIconNextType
    export const CaretSortUp: CarbonIconNextType
    export const CaretUp: CarbonIconNextType
    export const CarouselHorizontal: CarbonIconNextType
    export const CarouselVertical: CarbonIconNextType
    export const Catalog: CarbonIconNextType
    export const Categories: CarbonIconNextType
    export const Category: CarbonIconNextType
    export const CategoryAdd: CarbonIconNextType
    export const CategoryAnd: CarbonIconNextType
    export const CategoryNew: CarbonIconNextType
    export const CategoryNewEach: CarbonIconNextType
    export const Caution: CarbonIconNextType
    export const CautionInverted: CarbonIconNextType
    export const Cda: CarbonIconNextType
    export const CellTower: CarbonIconNextType
    export const CenterCircle: CarbonIconNextType
    export const CenterSquare: CarbonIconNextType
    export const CenterToFit: CarbonIconNextType
    export const Certificate: CarbonIconNextType
    export const CertificateCheck: CarbonIconNextType
    export const ChangeCatalog: CarbonIconNextType
    export const CharacterDecimal: CarbonIconNextType
    export const CharacterFraction: CarbonIconNextType
    export const CharacterInteger: CarbonIconNextType
    export const CharacterLowerCase: CarbonIconNextType
    export const CharacterNegativeNumber: CarbonIconNextType
    export const CharacterPatterns: CarbonIconNextType
    export const CharacterSentenceCase: CarbonIconNextType
    export const CharacterUpperCase: CarbonIconNextType
    export const CharacterWholeNumber: CarbonIconNextType
    export const ChargingStation: CarbonIconNextType
    export const ChargingStationFilled: CarbonIconNextType
    export const ChartArea: CarbonIconNextType
    export const ChartAreaSmooth: CarbonIconNextType
    export const ChartAreaStepper: CarbonIconNextType
    export const ChartAverage: CarbonIconNextType
    export const ChartBar: CarbonIconNextType
    export const ChartBarFloating: CarbonIconNextType
    export const ChartBarOverlay: CarbonIconNextType
    export const ChartBarStacked: CarbonIconNextType
    export const ChartBarTarget: CarbonIconNextType
    export const ChartBubble: CarbonIconNextType
    export const ChartBubblePacked: CarbonIconNextType
    export const ChartBullet: CarbonIconNextType
    export const ChartCandlestick: CarbonIconNextType
    export const ChartClusterBar: CarbonIconNextType
    export const ChartColumn: CarbonIconNextType
    export const ChartColumnFloating: CarbonIconNextType
    export const ChartColumnTarget: CarbonIconNextType
    export const ChartCombo: CarbonIconNextType
    export const ChartComboStacked: CarbonIconNextType
    export const ChartCustom: CarbonIconNextType
    export const ChartErrorBar: CarbonIconNextType
    export const ChartErrorBarAlt: CarbonIconNextType
    export const ChartEvaluation: CarbonIconNextType
    export const ChartHighLow: CarbonIconNextType
    export const ChartHistogram: CarbonIconNextType
    export const ChartLine: CarbonIconNextType
    export const ChartLineData: CarbonIconNextType
    export const ChartLineSmooth: CarbonIconNextType
    export const ChartMarimekko: CarbonIconNextType
    export const ChartMaximum: CarbonIconNextType
    export const ChartMedian: CarbonIconNextType
    export const ChartMinimum: CarbonIconNextType
    export const ChartMultiLine: CarbonIconNextType
    export const ChartMultitype: CarbonIconNextType
    export const ChartNetwork: CarbonIconNextType
    export const ChartParallel: CarbonIconNextType
    export const ChartPie: CarbonIconNextType
    export const ChartPoint: CarbonIconNextType
    export const ChartPopulation: CarbonIconNextType
    export const ChartRadar: CarbonIconNextType
    export const ChartRadial: CarbonIconNextType
    export const ChartRelationship: CarbonIconNextType
    export const ChartRing: CarbonIconNextType
    export const ChartRiver: CarbonIconNextType
    export const ChartRose: CarbonIconNextType
    export const ChartScatter: CarbonIconNextType
    export const ChartSpiral: CarbonIconNextType
    export const ChartStacked: CarbonIconNextType
    export const ChartStepper: CarbonIconNextType
    export const ChartSunburst: CarbonIconNextType
    export const ChartTSne: CarbonIconNextType
    export const ChartTreemap: CarbonIconNextType
    export const ChartVennDiagram: CarbonIconNextType
    export const ChartViolinPlot: CarbonIconNextType
    export const ChartWaterfall: CarbonIconNextType
    export const ChartWinLoss: CarbonIconNextType
    export const Chart_3D: CarbonIconNextType
    export const Chat: CarbonIconNextType
    export const ChatBot: CarbonIconNextType
    export const ChatLaunch: CarbonIconNextType
    export const ChatOff: CarbonIconNextType
    export const ChatOperational: CarbonIconNextType
    export const Checkbox: CarbonIconNextType
    export const CheckboxChecked: CarbonIconNextType
    export const CheckboxCheckedFilled: CarbonIconNextType
    export const CheckboxIndeterminate: CarbonIconNextType
    export const CheckboxIndeterminateFilled: CarbonIconNextType
    export const Checkmark: CarbonIconNextType
    export const CheckmarkFilled: CarbonIconNextType
    export const CheckmarkFilledError: CarbonIconNextType
    export const CheckmarkFilledWarning: CarbonIconNextType
    export const CheckmarkOutline: CarbonIconNextType
    export const CheckmarkOutlineError: CarbonIconNextType
    export const CheckmarkOutlineWarning: CarbonIconNextType
    export const Chemistry: CarbonIconNextType
    export const ChemistryReference: CarbonIconNextType
    export const ChevronDown: CarbonIconNextType
    export const ChevronLeft: CarbonIconNextType
    export const ChevronMini: CarbonIconNextType
    export const ChevronRight: CarbonIconNextType
    export const ChevronSort: CarbonIconNextType
    export const ChevronSortDown: CarbonIconNextType
    export const ChevronSortUp: CarbonIconNextType
    export const ChevronUp: CarbonIconNextType
    export const Chip: CarbonIconNextType
    export const Choices: CarbonIconNextType
    export const ChooseItem: CarbonIconNextType
    export const ChoroplethMap: CarbonIconNextType
    export const CicsCmas: CarbonIconNextType
    export const CicsExplorer: CarbonIconNextType
    export const CicsRegion: CarbonIconNextType
    export const CicsRegionRouting: CarbonIconNextType
    export const CicsRegionTarget: CarbonIconNextType
    export const CicsSystemGroup: CarbonIconNextType
    export const CicsWuiRegion: CarbonIconNextType
    export const Cicsplex: CarbonIconNextType
    export const CircleDash: CarbonIconNextType
    export const CircleFill: CarbonIconNextType
    export const CircleFilled: CarbonIconNextType
    export const CirclePacking: CarbonIconNextType
    export const CircleSolid: CarbonIconNextType
    export const CircleStroke: CarbonIconNextType
    export const Classification: CarbonIconNextType
    export const ClassifierLanguage: CarbonIconNextType
    export const Clean: CarbonIconNextType
    export const Close: CarbonIconNextType
    export const CloseFilled: CarbonIconNextType
    export const CloseOutline: CarbonIconNextType
    export const ClosedCaption: CarbonIconNextType
    export const ClosedCaptionAlt: CarbonIconNextType
    export const ClosedCaptionFilled: CarbonIconNextType
    export const Cloud: CarbonIconNextType
    export const CloudAlerting: CarbonIconNextType
    export const CloudApp: CarbonIconNextType
    export const CloudAuditing: CarbonIconNextType
    export const CloudCeiling: CarbonIconNextType
    export const CloudDataOps: CarbonIconNextType
    export const CloudDownload: CarbonIconNextType
    export const CloudFoundry_1: CarbonIconNextType
    export const CloudFoundry_2: CarbonIconNextType
    export const CloudLogging: CarbonIconNextType
    export const CloudMonitoring: CarbonIconNextType
    export const CloudOffline: CarbonIconNextType
    export const CloudRegistry: CarbonIconNextType
    export const CloudSatellite: CarbonIconNextType
    export const CloudSatelliteConfig: CarbonIconNextType
    export const CloudSatelliteLink: CarbonIconNextType
    export const CloudSatelliteServices: CarbonIconNextType
    export const CloudServiceManagement: CarbonIconNextType
    export const CloudServices: CarbonIconNextType
    export const CloudUpload: CarbonIconNextType
    export const Cloudy: CarbonIconNextType
    export const Code: CarbonIconNextType
    export const CodeHide: CarbonIconNextType
    export const CodeReference: CarbonIconNextType
    export const CodeSigningService: CarbonIconNextType
    export const Cognitive: CarbonIconNextType
    export const Collaborate: CarbonIconNextType
    export const CollapseAll: CarbonIconNextType
    export const CollapseCategories: CarbonIconNextType
    export const ColorPalette: CarbonIconNextType
    export const ColorSwitch: CarbonIconNextType
    export const Column: CarbonIconNextType
    export const ColumnDelete: CarbonIconNextType
    export const ColumnDependency: CarbonIconNextType
    export const ColumnInsert: CarbonIconNextType
    export const Commit: CarbonIconNextType
    export const CommunicationUnified: CarbonIconNextType
    export const Compare: CarbonIconNextType
    export const Compass: CarbonIconNextType
    export const Concept: CarbonIconNextType
    export const ConditionPoint: CarbonIconNextType
    export const ConditionWaitPoint: CarbonIconNextType
    export const Connect: CarbonIconNextType
    export const ConnectRecursive: CarbonIconNextType
    export const ConnectSource: CarbonIconNextType
    export const ConnectTarget: CarbonIconNextType
    export const ConnectionReceive: CarbonIconNextType
    export const ConnectionSend: CarbonIconNextType
    export const ConnectionSignal: CarbonIconNextType
    export const ConnectionSignalOff: CarbonIconNextType
    export const ConnectionTwoWay: CarbonIconNextType
    export const Construction: CarbonIconNextType
    export const ContainerRegistry: CarbonIconNextType
    export const ContainerServices: CarbonIconNextType
    export const ContainerSoftware: CarbonIconNextType
    export const ContentDeliveryNetwork: CarbonIconNextType
    export const ContentView: CarbonIconNextType
    export const Continue: CarbonIconNextType
    export const ContinueFilled: CarbonIconNextType
    export const Contrast: CarbonIconNextType
    export const ConvertToCloud: CarbonIconNextType
    export const Cookie: CarbonIconNextType
    export const Copy: CarbonIconNextType
    export const CopyFile: CarbonIconNextType
    export const CopyLink: CarbonIconNextType
    export const Corn: CarbonIconNextType
    export const Corner: CarbonIconNextType
    export const Coronavirus: CarbonIconNextType
    export const Cost: CarbonIconNextType
    export const CostTotal: CarbonIconNextType
    export const Cough: CarbonIconNextType
    export const Course: CarbonIconNextType
    export const Covariate: CarbonIconNextType
    export const Credentials: CarbonIconNextType
    export const Critical: CarbonIconNextType
    export const CriticalSeverity: CarbonIconNextType
    export const Crop: CarbonIconNextType
    export const CropGrowth: CarbonIconNextType
    export const CropHealth: CarbonIconNextType
    export const CrossTab: CarbonIconNextType
    export const Crossroads: CarbonIconNextType
    export const CrowdReport: CarbonIconNextType
    export const CrowdReportFilled: CarbonIconNextType
    export const Csv: CarbonIconNextType
    export const Cube: CarbonIconNextType
    export const CubeView: CarbonIconNextType
    export const Currency: CarbonIconNextType
    export const CurrencyBaht: CarbonIconNextType
    export const CurrencyDollar: CarbonIconNextType
    export const CurrencyEuro: CarbonIconNextType
    export const CurrencyLira: CarbonIconNextType
    export const CurrencyPound: CarbonIconNextType
    export const CurrencyRuble: CarbonIconNextType
    export const CurrencyRupee: CarbonIconNextType
    export const CurrencyShekel: CarbonIconNextType
    export const CurrencyWon: CarbonIconNextType
    export const CurrencyYen: CarbonIconNextType
    export const Cursor_1: CarbonIconNextType
    export const Cursor_2: CarbonIconNextType
    export const Cut: CarbonIconNextType
    export const CutOut: CarbonIconNextType
    export const Cyclist: CarbonIconNextType
    export const Dashboard: CarbonIconNextType
    export const DashboardReference: CarbonIconNextType
    export const DataAccessor: CarbonIconNextType
    export const DataBackup: CarbonIconNextType
    export const DataBase: CarbonIconNextType
    export const DataBaseAlt: CarbonIconNextType
    export const DataBin: CarbonIconNextType
    export const DataBlob: CarbonIconNextType
    export const DataCenter: CarbonIconNextType
    export const DataCheck: CarbonIconNextType
    export const DataClass: CarbonIconNextType
    export const DataCollection: CarbonIconNextType
    export const DataConnected: CarbonIconNextType
    export const DataDefinition: CarbonIconNextType
    export const DataDiode: CarbonIconNextType
    export const DataEnrichment: CarbonIconNextType
    export const DataEnrichmentAdd: CarbonIconNextType
    export const DataError: CarbonIconNextType
    export const DataFormat: CarbonIconNextType
    export const DataPlayer: CarbonIconNextType
    export const DataQualityDefinition: CarbonIconNextType
    export const DataReference: CarbonIconNextType
    export const DataRefinery: CarbonIconNextType
    export const DataRefineryReference: CarbonIconNextType
    export const DataSet: CarbonIconNextType
    export const DataShare: CarbonIconNextType
    export const DataStructured: CarbonIconNextType
    export const DataTable: CarbonIconNextType
    export const DataTableReference: CarbonIconNextType
    export const DataUnstructured: CarbonIconNextType
    export const DataView: CarbonIconNextType
    export const DataViewAlt: CarbonIconNextType
    export const DataVis_1: CarbonIconNextType
    export const DataVis_2: CarbonIconNextType
    export const DataVis_3: CarbonIconNextType
    export const DataVis_4: CarbonIconNextType
    export const Data_1: CarbonIconNextType
    export const Data_2: CarbonIconNextType
    export const DatabaseDatastax: CarbonIconNextType
    export const DatabaseElastic: CarbonIconNextType
    export const DatabaseEnterpriseDb2: CarbonIconNextType
    export const DatabaseEtcd: CarbonIconNextType
    export const DatabaseMongodb: CarbonIconNextType
    export const DatabasePostgreSql: CarbonIconNextType
    export const DatabaseRabbit: CarbonIconNextType
    export const DatabaseRedis: CarbonIconNextType
    export const Datastore: CarbonIconNextType
    export const Debug: CarbonIconNextType
    export const DecisionTree: CarbonIconNextType
    export const Delivery: CarbonIconNextType
    export const DeliveryAdd: CarbonIconNextType
    export const DeliveryParcel: CarbonIconNextType
    export const DeliveryTruck: CarbonIconNextType
    export const Departure: CarbonIconNextType
    export const Deploy: CarbonIconNextType
    export const DeployRules: CarbonIconNextType
    export const DeploymentPattern: CarbonIconNextType
    export const DeploymentPolicy: CarbonIconNextType
    export const DeploymentUnitData: CarbonIconNextType
    export const DeploymentUnitExecution: CarbonIconNextType
    export const DeploymentUnitInstallation: CarbonIconNextType
    export const DeploymentUnitPresentation: CarbonIconNextType
    export const DeploymentUnitTechnicalData: CarbonIconNextType
    export const DeploymentUnitTechnicalExecution: CarbonIconNextType
    export const DeploymentUnitTechnicalInstallation: CarbonIconNextType
    export const DeploymentUnitTechnicalPresentation: CarbonIconNextType
    export const DeskAdjustable: CarbonIconNextType
    export const Development: CarbonIconNextType
    export const Devices: CarbonIconNextType
    export const DewPoint: CarbonIconNextType
    export const DewPointFilled: CarbonIconNextType
    export const Diagram: CarbonIconNextType
    export const DiagramReference: CarbonIconNextType
    export const DirectLink: CarbonIconNextType
    export const DirectionBearRight_01: CarbonIconNextType
    export const DirectionBearRight_01Filled: CarbonIconNextType
    export const DirectionBearRight_02: CarbonIconNextType
    export const DirectionBearRight_02Filled: CarbonIconNextType
    export const DirectionCurve: CarbonIconNextType
    export const DirectionCurveFilled: CarbonIconNextType
    export const DirectionFork: CarbonIconNextType
    export const DirectionForkFilled: CarbonIconNextType
    export const DirectionLoopLeft: CarbonIconNextType
    export const DirectionLoopLeftFilled: CarbonIconNextType
    export const DirectionLoopRight: CarbonIconNextType
    export const DirectionLoopRightFilled: CarbonIconNextType
    export const DirectionMerge: CarbonIconNextType
    export const DirectionMergeFilled: CarbonIconNextType
    export const DirectionRight_01: CarbonIconNextType
    export const DirectionRight_01Filled: CarbonIconNextType
    export const DirectionRight_02: CarbonIconNextType
    export const DirectionRight_02Filled: CarbonIconNextType
    export const DirectionRotaryFirstRight: CarbonIconNextType
    export const DirectionRotaryFirstRightFilled: CarbonIconNextType
    export const DirectionRotaryRight: CarbonIconNextType
    export const DirectionRotaryRightFilled: CarbonIconNextType
    export const DirectionRotaryStraight: CarbonIconNextType
    export const DirectionRotaryStraightFilled: CarbonIconNextType
    export const DirectionSharpTurn: CarbonIconNextType
    export const DirectionSharpTurnFilled: CarbonIconNextType
    export const DirectionStraight: CarbonIconNextType
    export const DirectionStraightFilled: CarbonIconNextType
    export const DirectionStraightRight: CarbonIconNextType
    export const DirectionStraightRightFilled: CarbonIconNextType
    export const DirectionUTurn: CarbonIconNextType
    export const DirectionUTurnFilled: CarbonIconNextType
    export const DirectoryDomain: CarbonIconNextType
    export const DistributeHorizontalCenter: CarbonIconNextType
    export const DistributeHorizontalLeft: CarbonIconNextType
    export const DistributeHorizontalRight: CarbonIconNextType
    export const DistributeVerticalBottom: CarbonIconNextType
    export const DistributeVerticalCenter: CarbonIconNextType
    export const DistributeVerticalTop: CarbonIconNextType
    export const DnsServices: CarbonIconNextType
    export const Doc: CarbonIconNextType
    export const Document: CarbonIconNextType
    export const DocumentAdd: CarbonIconNextType
    export const DocumentAttachment: CarbonIconNextType
    export const DocumentAudio: CarbonIconNextType
    export const DocumentBlank: CarbonIconNextType
    export const DocumentDownload: CarbonIconNextType
    export const DocumentEpdf: CarbonIconNextType
    export const DocumentExport: CarbonIconNextType
    export const DocumentHorizontal: CarbonIconNextType
    export const DocumentImport: CarbonIconNextType
    export const DocumentPdf: CarbonIconNextType
    export const DocumentPreliminary: CarbonIconNextType
    export const DocumentProtected: CarbonIconNextType
    export const DocumentSecurity: CarbonIconNextType
    export const DocumentSentiment: CarbonIconNextType
    export const DocumentSigned: CarbonIconNextType
    export const DocumentSketch: CarbonIconNextType
    export const DocumentSubtract: CarbonIconNextType
    export const DocumentTasks: CarbonIconNextType
    export const DocumentUnknown: CarbonIconNextType
    export const DocumentUnprotected: CarbonIconNextType
    export const DocumentVertical: CarbonIconNextType
    export const DocumentVideo: CarbonIconNextType
    export const DocumentView: CarbonIconNextType
    export const DocumentWordProcessor: CarbonIconNextType
    export const DocumentWordProcessorReference: CarbonIconNextType
    export const DogWalker: CarbonIconNextType
    export const DotMark: CarbonIconNextType
    export const DoubleInteger: CarbonIconNextType
    export const DownToBottom: CarbonIconNextType
    export const Download: CarbonIconNextType
    export const DragHorizontal: CarbonIconNextType
    export const DragVertical: CarbonIconNextType
    export const Draggable: CarbonIconNextType
    export const Draw: CarbonIconNextType
    export const DrillBack: CarbonIconNextType
    export const DrillDown: CarbonIconNextType
    export const DrillThrough: CarbonIconNextType
    export const DriverAnalysis: CarbonIconNextType
    export const Drone: CarbonIconNextType
    export const DroneDelivery: CarbonIconNextType
    export const DroneFront: CarbonIconNextType
    export const DroneVideo: CarbonIconNextType
    export const DropPhoto: CarbonIconNextType
    export const DropPhotoFilled: CarbonIconNextType
    export const Drought: CarbonIconNextType
    export const Dvr: CarbonIconNextType
    export const Earth: CarbonIconNextType
    export const EarthAmericas: CarbonIconNextType
    export const EarthAmericasFilled: CarbonIconNextType
    export const EarthEuropeAfrica: CarbonIconNextType
    export const EarthEuropeAfricaFilled: CarbonIconNextType
    export const EarthFilled: CarbonIconNextType
    export const EarthSoutheastAsia: CarbonIconNextType
    export const EarthSoutheastAsiaFilled: CarbonIconNextType
    export const Earthquake: CarbonIconNextType
    export const EdgeCluster: CarbonIconNextType
    export const EdgeDevice: CarbonIconNextType
    export const EdgeNode: CarbonIconNextType
    export const EdgeNodeAlt: CarbonIconNextType
    export const EdgeService: CarbonIconNextType
    export const Edit: CarbonIconNextType
    export const EditOff: CarbonIconNextType
    export const EdtLoop: CarbonIconNextType
    export const Education: CarbonIconNextType
    export const Email: CarbonIconNextType
    export const EmailNew: CarbonIconNextType
    export const Encryption: CarbonIconNextType
    export const EnergyRenewable: CarbonIconNextType
    export const Enterprise: CarbonIconNextType
    export const Equalizer: CarbonIconNextType
    export const Erase: CarbonIconNextType
    export const Error: CarbonIconNextType
    export const ErrorFilled: CarbonIconNextType
    export const ErrorOutline: CarbonIconNextType
    export const Event: CarbonIconNextType
    export const EventSchedule: CarbonIconNextType
    export const Events: CarbonIconNextType
    export const EventsAlt: CarbonIconNextType
    export const ExamMode: CarbonIconNextType
    export const Exit: CarbonIconNextType
    export const ExpandAll: CarbonIconNextType
    export const ExpandCategories: CarbonIconNextType
    export const Explore: CarbonIconNextType
    export const Export: CarbonIconNextType
    export const Eyedropper: CarbonIconNextType
    export const FaceActivated: CarbonIconNextType
    export const FaceActivatedAdd: CarbonIconNextType
    export const FaceActivatedFilled: CarbonIconNextType
    export const FaceAdd: CarbonIconNextType
    export const FaceCool: CarbonIconNextType
    export const FaceDissatisfied: CarbonIconNextType
    export const FaceDissatisfiedFilled: CarbonIconNextType
    export const FaceDizzy: CarbonIconNextType
    export const FaceDizzyFilled: CarbonIconNextType
    export const FaceMask: CarbonIconNextType
    export const FaceNeutral: CarbonIconNextType
    export const FaceNeutralFilled: CarbonIconNextType
    export const FacePending: CarbonIconNextType
    export const FacePendingFilled: CarbonIconNextType
    export const FaceSatisfied: CarbonIconNextType
    export const FaceSatisfiedFilled: CarbonIconNextType
    export const FaceWink: CarbonIconNextType
    export const FaceWinkFilled: CarbonIconNextType
    export const Factor: CarbonIconNextType
    export const Fade: CarbonIconNextType
    export const Favorite: CarbonIconNextType
    export const FavoriteFilled: CarbonIconNextType
    export const FavoriteHalf: CarbonIconNextType
    export const FetchUpload: CarbonIconNextType
    export const FetchUploadCloud: CarbonIconNextType
    export const FileStorage: CarbonIconNextType
    export const Filter: CarbonIconNextType
    export const FilterEdit: CarbonIconNextType
    export const FilterRemove: CarbonIconNextType
    export const FilterReset: CarbonIconNextType
    export const Finance: CarbonIconNextType
    export const FingerprintRecognition: CarbonIconNextType
    export const Fire: CarbonIconNextType
    export const Firewall: CarbonIconNextType
    export const FirewallClassic: CarbonIconNextType
    export const Fish: CarbonIconNextType
    export const FishMultiple: CarbonIconNextType
    export const FitToHeight: CarbonIconNextType
    export const FitToScreen: CarbonIconNextType
    export const FitToWidth: CarbonIconNextType
    export const Flag: CarbonIconNextType
    export const FlagFilled: CarbonIconNextType
    export const FlaggingTaxi: CarbonIconNextType
    export const Flash: CarbonIconNextType
    export const FlashFilled: CarbonIconNextType
    export const FlashOff: CarbonIconNextType
    export const FlashOffFilled: CarbonIconNextType
    export const FlightInternational: CarbonIconNextType
    export const FlightRoster: CarbonIconNextType
    export const FlightSchedule: CarbonIconNextType
    export const FloatingIp: CarbonIconNextType
    export const Flood: CarbonIconNextType
    export const FloodWarning: CarbonIconNextType
    export const Floorplan: CarbonIconNextType
    export const Flow: CarbonIconNextType
    export const FlowConnection: CarbonIconNextType
    export const FlowData: CarbonIconNextType
    export const FlowLogsVpc: CarbonIconNextType
    export const FlowModeler: CarbonIconNextType
    export const FlowModelerReference: CarbonIconNextType
    export const FlowStream: CarbonIconNextType
    export const FlowStreamReference: CarbonIconNextType
    export const Fog: CarbonIconNextType
    export const Folder: CarbonIconNextType
    export const FolderAdd: CarbonIconNextType
    export const FolderDetails: CarbonIconNextType
    export const FolderDetailsReference: CarbonIconNextType
    export const FolderMoveTo: CarbonIconNextType
    export const FolderOff: CarbonIconNextType
    export const FolderOpen: CarbonIconNextType
    export const FolderParent: CarbonIconNextType
    export const FolderShared: CarbonIconNextType
    export const Folders: CarbonIconNextType
    export const ForecastHail: CarbonIconNextType
    export const ForecastHail_30: CarbonIconNextType
    export const ForecastLightning: CarbonIconNextType
    export const ForecastLightning_30: CarbonIconNextType
    export const Fork: CarbonIconNextType
    export const Forum: CarbonIconNextType
    export const Forward_10: CarbonIconNextType
    export const Forward_30: CarbonIconNextType
    export const Forward_5: CarbonIconNextType
    export const Fragile: CarbonIconNextType
    export const Friendship: CarbonIconNextType
    export const FruitBowl: CarbonIconNextType
    export const Function: CarbonIconNextType
    export const FunctionMath: CarbonIconNextType
    export const GameConsole: CarbonIconNextType
    export const GameWireless: CarbonIconNextType
    export const Gamification: CarbonIconNextType
    export const GasStation: CarbonIconNextType
    export const GasStationFilled: CarbonIconNextType
    export const Gateway: CarbonIconNextType
    export const GatewayApi: CarbonIconNextType
    export const GatewayMail: CarbonIconNextType
    export const GatewayPublic: CarbonIconNextType
    export const GatewaySecurity: CarbonIconNextType
    export const GatewayUserAccess: CarbonIconNextType
    export const GatewayVpn: CarbonIconNextType
    export const GenderFemale: CarbonIconNextType
    export const GenderMale: CarbonIconNextType
    export const GeneratePdf: CarbonIconNextType
    export const Gif: CarbonIconNextType
    export const Gift: CarbonIconNextType
    export const Globe: CarbonIconNextType
    export const Gradient: CarbonIconNextType
    export const GraphicalDataFlow: CarbonIconNextType
    export const Grid: CarbonIconNextType
    export const Group: CarbonIconNextType
    export const GroupAccess: CarbonIconNextType
    export const GroupAccount: CarbonIconNextType
    export const GroupObjects: CarbonIconNextType
    export const GroupObjectsNew: CarbonIconNextType
    export const GroupObjectsSave: CarbonIconNextType
    export const GroupPresentation: CarbonIconNextType
    export const GroupResource: CarbonIconNextType
    export const GroupSecurity: CarbonIconNextType
    export const Growth: CarbonIconNextType
    export const Gui: CarbonIconNextType
    export const GuiManagement: CarbonIconNextType
    export const Hail: CarbonIconNextType
    export const Harbor: CarbonIconNextType
    export const HardwareSecurityModule: CarbonIconNextType
    export const Hashtag: CarbonIconNextType
    export const Haze: CarbonIconNextType
    export const HazeNight: CarbonIconNextType
    export const Hd: CarbonIconNextType
    export const HdFilled: CarbonIconNextType
    export const Hdr: CarbonIconNextType
    export const Headphones: CarbonIconNextType
    export const Headset: CarbonIconNextType
    export const HealthCross: CarbonIconNextType
    export const Hearing: CarbonIconNextType
    export const HeatMap: CarbonIconNextType
    export const HeatMapStocks: CarbonIconNextType
    export const HeatMap_02: CarbonIconNextType
    export const HeatMap_03: CarbonIconNextType
    export const Helicopter: CarbonIconNextType
    export const Help: CarbonIconNextType
    export const HelpDesk: CarbonIconNextType
    export const HelpFilled: CarbonIconNextType
    export const Home: CarbonIconNextType
    export const HorizontalView: CarbonIconNextType
    export const Hospital: CarbonIconNextType
    export const HospitalBed: CarbonIconNextType
    export const Hotel: CarbonIconNextType
    export const Hourglass: CarbonIconNextType
    export const Html: CarbonIconNextType
    export const HtmlReference: CarbonIconNextType
    export const Http: CarbonIconNextType
    export const Humidity: CarbonIconNextType
    export const HumidityAlt: CarbonIconNextType
    export const Hurricane: CarbonIconNextType
    export const HybridNetworking: CarbonIconNextType
    export const HybridNetworkingAlt: CarbonIconNextType
    export const IbmCloud: CarbonIconNextType
    export const IbmCloudDedicatedHost: CarbonIconNextType
    export const IbmCloudInternetServices: CarbonIconNextType
    export const IbmCloudPakApplications: CarbonIconNextType
    export const IbmCloudPakBusinessAutomation: CarbonIconNextType
    export const IbmCloudPakData: CarbonIconNextType
    export const IbmCloudPakIntegration: CarbonIconNextType
    export const IbmCloudPakMantaAutomatedDataLineage: CarbonIconNextType
    export const IbmCloudPakMulticloudMgmt: CarbonIconNextType
    export const IbmCloudPakNetworkAutomation: CarbonIconNextType
    export const IbmCloudPakSecurity: CarbonIconNextType
    export const IbmCloudPakSystem: CarbonIconNextType
    export const IbmCloudPakWatsonAiops: CarbonIconNextType
    export const IbmCloudSecurityComplianceCenter: CarbonIconNextType
    export const IbmCloudSubnets: CarbonIconNextType
    export const IbmCloudTransitGateway: CarbonIconNextType
    export const IbmCloudVpcEndpoints: CarbonIconNextType
    export const IbmDataReplication: CarbonIconNextType
    export const IbmMatch_360: CarbonIconNextType
    export const IbmOpenEnterpriseLanguages: CarbonIconNextType
    export const IbmSecurity: CarbonIconNextType
    export const IbmSecurityServices: CarbonIconNextType
    export const IbmWatsonOrders: CarbonIconNextType
    export const IbmZCloudModStack: CarbonIconNextType
    export const IbmZCloudProvisioning: CarbonIconNextType
    export const IbmZOsPackageManager: CarbonIconNextType
    export const IceAccretion: CarbonIconNextType
    export const IceVision: CarbonIconNextType
    export const Icon: CarbonIconNextType
    export const IdManagement: CarbonIconNextType
    export const Idea: CarbonIconNextType
    export const Identification: CarbonIconNextType
    export const Image: CarbonIconNextType
    export const ImageCopy: CarbonIconNextType
    export const ImageMedical: CarbonIconNextType
    export const ImageReference: CarbonIconNextType
    export const ImageSearch: CarbonIconNextType
    export const ImageSearchAlt: CarbonIconNextType
    export const ImageService: CarbonIconNextType
    export const ImportExport: CarbonIconNextType
    export const ImproveRelevance: CarbonIconNextType
    export const InProgress: CarbonIconNextType
    export const InProgressError: CarbonIconNextType
    export const InProgressWarning: CarbonIconNextType
    export const Incomplete: CarbonIconNextType
    export const IncompleteCancel: CarbonIconNextType
    export const IncompleteError: CarbonIconNextType
    export const IncompleteWarning: CarbonIconNextType
    export const IncreaseLevel: CarbonIconNextType
    export const Industry: CarbonIconNextType
    export const Information: CarbonIconNextType
    export const InformationDisabled: CarbonIconNextType
    export const InformationFilled: CarbonIconNextType
    export const InformationSquare: CarbonIconNextType
    export const InformationSquareFilled: CarbonIconNextType
    export const InfrastructureClassic: CarbonIconNextType
    export const Insert: CarbonIconNextType
    export const InsertPage: CarbonIconNextType
    export const InsertSyntax: CarbonIconNextType
    export const Inspection: CarbonIconNextType
    export const InstanceBx: CarbonIconNextType
    export const InstanceClassic: CarbonIconNextType
    export const InstanceCx: CarbonIconNextType
    export const InstanceMx: CarbonIconNextType
    export const InstanceVirtual: CarbonIconNextType
    export const Integration: CarbonIconNextType
    export const IntentRequestActive: CarbonIconNextType
    export const IntentRequestCreate: CarbonIconNextType
    export const IntentRequestHeal: CarbonIconNextType
    export const IntentRequestInactive: CarbonIconNextType
    export const IntentRequestScaleIn: CarbonIconNextType
    export const IntentRequestScaleOut: CarbonIconNextType
    export const IntentRequestUninstall: CarbonIconNextType
    export const IntentRequestUpgrade: CarbonIconNextType
    export const Interactions: CarbonIconNextType
    export const Intersect: CarbonIconNextType
    export const IntrusionPrevention: CarbonIconNextType
    export const InventoryManagement: CarbonIconNextType
    export const IotConnect: CarbonIconNextType
    export const IotPlatform: CarbonIconNextType
    export const Iso: CarbonIconNextType
    export const IsoFilled: CarbonIconNextType
    export const IsoOutline: CarbonIconNextType
    export const JoinFull: CarbonIconNextType
    export const JoinInner: CarbonIconNextType
    export const JoinLeft: CarbonIconNextType
    export const JoinOuter: CarbonIconNextType
    export const JoinRight: CarbonIconNextType
    export const Jpg: CarbonIconNextType
    export const Json: CarbonIconNextType
    export const JsonReference: CarbonIconNextType
    export const JumpLink: CarbonIconNextType
    export const KeepDry: CarbonIconNextType
    export const Keyboard: CarbonIconNextType
    export const Kubernetes: CarbonIconNextType
    export const Label: CarbonIconNextType
    export const Language: CarbonIconNextType
    export const Laptop: CarbonIconNextType
    export const Lasso: CarbonIconNextType
    export const LassoPolygon: CarbonIconNextType
    export const Launch: CarbonIconNextType
    export const Layers: CarbonIconNextType
    export const Legend: CarbonIconNextType
    export const LetterAa: CarbonIconNextType
    export const LetterBb: CarbonIconNextType
    export const LetterCc: CarbonIconNextType
    export const LetterDd: CarbonIconNextType
    export const LetterEe: CarbonIconNextType
    export const LetterFf: CarbonIconNextType
    export const LetterGg: CarbonIconNextType
    export const LetterHh: CarbonIconNextType
    export const LetterIi: CarbonIconNextType
    export const LetterJj: CarbonIconNextType
    export const LetterKk: CarbonIconNextType
    export const LetterLl: CarbonIconNextType
    export const LetterMm: CarbonIconNextType
    export const LetterNn: CarbonIconNextType
    export const LetterOo: CarbonIconNextType
    export const LetterPp: CarbonIconNextType
    export const LetterQq: CarbonIconNextType
    export const LetterRr: CarbonIconNextType
    export const LetterSs: CarbonIconNextType
    export const LetterTt: CarbonIconNextType
    export const LetterUu: CarbonIconNextType
    export const LetterVv: CarbonIconNextType
    export const LetterWw: CarbonIconNextType
    export const LetterXx: CarbonIconNextType
    export const LetterYy: CarbonIconNextType
    export const LetterZz: CarbonIconNextType
    export const License: CarbonIconNextType
    export const LicenseDraft: CarbonIconNextType
    export const LicenseGlobal: CarbonIconNextType
    export const LicenseMaintenance: CarbonIconNextType
    export const LicenseMaintenanceDraft: CarbonIconNextType
    export const LicenseThirdParty: CarbonIconNextType
    export const LicenseThirdPartyDraft: CarbonIconNextType
    export const Lifesaver: CarbonIconNextType
    export const Light: CarbonIconNextType
    export const LightFilled: CarbonIconNextType
    export const Lightning: CarbonIconNextType
    export const Link: CarbonIconNextType
    export const Linux: CarbonIconNextType
    export const LinuxAlt: CarbonIconNextType
    export const List: CarbonIconNextType
    export const ListBoxes: CarbonIconNextType
    export const ListBulleted: CarbonIconNextType
    export const ListChecked: CarbonIconNextType
    export const ListDropdown: CarbonIconNextType
    export const ListNumbered: CarbonIconNextType
    export const LoadBalancerApplication: CarbonIconNextType
    export const LoadBalancerClassic: CarbonIconNextType
    export const LoadBalancerGlobal: CarbonIconNextType
    export const LoadBalancerListener: CarbonIconNextType
    export const LoadBalancerLocal: CarbonIconNextType
    export const LoadBalancerNetwork: CarbonIconNextType
    export const LoadBalancerPool: CarbonIconNextType
    export const LoadBalancerVpc: CarbonIconNextType
    export const Location: CarbonIconNextType
    export const LocationCompany: CarbonIconNextType
    export const LocationCompanyFilled: CarbonIconNextType
    export const LocationCurrent: CarbonIconNextType
    export const LocationFilled: CarbonIconNextType
    export const LocationHazard: CarbonIconNextType
    export const LocationHazardFilled: CarbonIconNextType
    export const LocationHeart: CarbonIconNextType
    export const LocationHeartFilled: CarbonIconNextType
    export const LocationPerson: CarbonIconNextType
    export const LocationPersonFilled: CarbonIconNextType
    export const LocationSave: CarbonIconNextType
    export const LocationStar: CarbonIconNextType
    export const LocationStarFilled: CarbonIconNextType
    export const Locked: CarbonIconNextType
    export const LogicalPartition: CarbonIconNextType
    export const Login: CarbonIconNextType
    export const LogoDigg: CarbonIconNextType
    export const LogoDiscord: CarbonIconNextType
    export const LogoFacebook: CarbonIconNextType
    export const LogoFlickr: CarbonIconNextType
    export const LogoGithub: CarbonIconNextType
    export const LogoGlassdoor: CarbonIconNextType
    export const LogoInstagram: CarbonIconNextType
    export const LogoJupyter: CarbonIconNextType
    export const LogoKeybase: CarbonIconNextType
    export const LogoKubernetes: CarbonIconNextType
    export const LogoLinkedin: CarbonIconNextType
    export const LogoLivestream: CarbonIconNextType
    export const LogoMedium: CarbonIconNextType
    export const LogoOpenshift: CarbonIconNextType
    export const LogoPinterest: CarbonIconNextType
    export const LogoPython: CarbonIconNextType
    export const LogoQuora: CarbonIconNextType
    export const LogoRScript: CarbonIconNextType
    export const LogoSkype: CarbonIconNextType
    export const LogoSlack: CarbonIconNextType
    export const LogoSnapchat: CarbonIconNextType
    export const LogoTumblr: CarbonIconNextType
    export const LogoTwitter: CarbonIconNextType
    export const LogoVmware: CarbonIconNextType
    export const LogoWechat: CarbonIconNextType
    export const LogoXing: CarbonIconNextType
    export const LogoYelp: CarbonIconNextType
    export const LogoYoutube: CarbonIconNextType
    export const Logout: CarbonIconNextType
    export const Loop: CarbonIconNextType
    export const LowSeverity: CarbonIconNextType
    export const MacCommand: CarbonIconNextType
    export const MacOption: CarbonIconNextType
    export const MacShift: CarbonIconNextType
    export const MachineLearning: CarbonIconNextType
    export const MachineLearningModel: CarbonIconNextType
    export const MagicWand: CarbonIconNextType
    export const MagicWandFilled: CarbonIconNextType
    export const MailAll: CarbonIconNextType
    export const MailReply: CarbonIconNextType
    export const ManageProtection: CarbonIconNextType
    export const ManagedSolutions: CarbonIconNextType
    export const Map: CarbonIconNextType
    export const MapBoundary: CarbonIconNextType
    export const MapBoundaryVegetation: CarbonIconNextType
    export const MapCenter: CarbonIconNextType
    export const MapIdentify: CarbonIconNextType
    export const MarineWarning: CarbonIconNextType
    export const MathCurve: CarbonIconNextType
    export const Maximize: CarbonIconNextType
    export const MediaCast: CarbonIconNextType
    export const MediaLibrary: CarbonIconNextType
    export const MediaLibraryFilled: CarbonIconNextType
    export const Medication: CarbonIconNextType
    export const MedicationAlert: CarbonIconNextType
    export const MedicationReminder: CarbonIconNextType
    export const Menu: CarbonIconNextType
    export const MessageQueue: CarbonIconNextType
    export const Meter: CarbonIconNextType
    export const MeterAlt: CarbonIconNextType
    export const Microphone: CarbonIconNextType
    export const MicrophoneFilled: CarbonIconNextType
    export const MicrophoneOff: CarbonIconNextType
    export const MicrophoneOffFilled: CarbonIconNextType
    export const Microscope: CarbonIconNextType
    export const Microservices_1: CarbonIconNextType
    export const Microservices_2: CarbonIconNextType
    export const Migrate: CarbonIconNextType
    export const MigrateAlt: CarbonIconNextType
    export const Milestone: CarbonIconNextType
    export const MilitaryCamp: CarbonIconNextType
    export const Minimize: CarbonIconNextType
    export const Misuse: CarbonIconNextType
    export const MisuseOutline: CarbonIconNextType
    export const MixedRainHail: CarbonIconNextType
    export const Mobile: CarbonIconNextType
    export const MobileAdd: CarbonIconNextType
    export const MobileAudio: CarbonIconNextType
    export const MobileCheck: CarbonIconNextType
    export const MobileDownload: CarbonIconNextType
    export const MobileLandscape: CarbonIconNextType
    export const MobilityServices: CarbonIconNextType
    export const Model: CarbonIconNextType
    export const ModelAlt: CarbonIconNextType
    export const ModelBuilder: CarbonIconNextType
    export const ModelBuilderReference: CarbonIconNextType
    export const ModelReference: CarbonIconNextType
    export const Money: CarbonIconNextType
    export const Monster: CarbonIconNextType
    export const Monument: CarbonIconNextType
    export const Moon: CarbonIconNextType
    export const Moonrise: CarbonIconNextType
    export const Moonset: CarbonIconNextType
    export const MostlyCloudy: CarbonIconNextType
    export const MostlyCloudyNight: CarbonIconNextType
    export const Mountain: CarbonIconNextType
    export const Mov: CarbonIconNextType
    export const Move: CarbonIconNextType
    export const Movement: CarbonIconNextType
    export const Mp3: CarbonIconNextType
    export const Mp4: CarbonIconNextType
    export const Mpeg: CarbonIconNextType
    export const Mpg2: CarbonIconNextType
    export const Music: CarbonIconNextType
    export const MusicAdd: CarbonIconNextType
    export const MusicRemove: CarbonIconNextType
    export const NameSpace: CarbonIconNextType
    export const NavaidCivil: CarbonIconNextType
    export const NavaidDme: CarbonIconNextType
    export const NavaidHelipad: CarbonIconNextType
    export const NavaidMilitary: CarbonIconNextType
    export const NavaidMilitaryCivil: CarbonIconNextType
    export const NavaidNdb: CarbonIconNextType
    export const NavaidNdbDme: CarbonIconNextType
    export const NavaidPrivate: CarbonIconNextType
    export const NavaidSeaplane: CarbonIconNextType
    export const NavaidTacan: CarbonIconNextType
    export const NavaidVhfor: CarbonIconNextType
    export const NavaidVor: CarbonIconNextType
    export const NavaidVordme: CarbonIconNextType
    export const NavaidVortac: CarbonIconNextType
    export const Need: CarbonIconNextType
    export const NetworkAdminControl: CarbonIconNextType
    export const NetworkEnterprise: CarbonIconNextType
    export const NetworkOverlay: CarbonIconNextType
    export const NetworkPublic: CarbonIconNextType
    export const Network_1: CarbonIconNextType
    export const Network_2: CarbonIconNextType
    export const Network_3: CarbonIconNextType
    export const Network_3Reference: CarbonIconNextType
    export const Network_4: CarbonIconNextType
    export const Network_4Reference: CarbonIconNextType
    export const NewTab: CarbonIconNextType
    export const NextFilled: CarbonIconNextType
    export const NextOutline: CarbonIconNextType
    export const NoImage: CarbonIconNextType
    export const NoTicket: CarbonIconNextType
    export const Nominal: CarbonIconNextType
    export const NonCertified: CarbonIconNextType
    export const NoodleBowl: CarbonIconNextType
    export const NotAvailable: CarbonIconNextType
    export const NotSent: CarbonIconNextType
    export const NotSentFilled: CarbonIconNextType
    export const Notebook: CarbonIconNextType
    export const NotebookReference: CarbonIconNextType
    export const Notification: CarbonIconNextType
    export const NotificationFilled: CarbonIconNextType
    export const NotificationNew: CarbonIconNextType
    export const NotificationOff: CarbonIconNextType
    export const NotificationOffFilled: CarbonIconNextType
    export const NumberSmall_0: CarbonIconNextType
    export const NumberSmall_1: CarbonIconNextType
    export const NumberSmall_2: CarbonIconNextType
    export const NumberSmall_3: CarbonIconNextType
    export const NumberSmall_4: CarbonIconNextType
    export const NumberSmall_5: CarbonIconNextType
    export const NumberSmall_6: CarbonIconNextType
    export const NumberSmall_7: CarbonIconNextType
    export const NumberSmall_8: CarbonIconNextType
    export const NumberSmall_9: CarbonIconNextType
    export const Number_0: CarbonIconNextType
    export const Number_1: CarbonIconNextType
    export const Number_2: CarbonIconNextType
    export const Number_3: CarbonIconNextType
    export const Number_4: CarbonIconNextType
    export const Number_5: CarbonIconNextType
    export const Number_6: CarbonIconNextType
    export const Number_7: CarbonIconNextType
    export const Number_8: CarbonIconNextType
    export const Number_9: CarbonIconNextType
    export const ObjectStorage: CarbonIconNextType
    export const ObjectStorageAlt: CarbonIconNextType
    export const ObservedHail: CarbonIconNextType
    export const ObservedLightning: CarbonIconNextType
    export const Omega: CarbonIconNextType
    export const Opacity: CarbonIconNextType
    export const OpenPanelBottom: CarbonIconNextType
    export const OpenPanelFilledBottom: CarbonIconNextType
    export const OpenPanelFilledLeft: CarbonIconNextType
    export const OpenPanelFilledRight: CarbonIconNextType
    export const OpenPanelFilledTop: CarbonIconNextType
    export const OpenPanelLeft: CarbonIconNextType
    export const OpenPanelRight: CarbonIconNextType
    export const OpenPanelTop: CarbonIconNextType
    export const OperationsField: CarbonIconNextType
    export const OperationsRecord: CarbonIconNextType
    export const OrderDetails: CarbonIconNextType
    export const Ordinal: CarbonIconNextType
    export const Outage: CarbonIconNextType
    export const OutlookSevere: CarbonIconNextType
    export const OverflowMenuHorizontal: CarbonIconNextType
    export const OverflowMenuVertical: CarbonIconNextType
    export const Overlay: CarbonIconNextType
    export const Package: CarbonIconNextType
    export const PageBreak: CarbonIconNextType
    export const PageFirst: CarbonIconNextType
    export const PageLast: CarbonIconNextType
    export const PageNumber: CarbonIconNextType
    export const PaintBrush: CarbonIconNextType
    export const PaintBrushAlt: CarbonIconNextType
    export const PalmTree: CarbonIconNextType
    export const PanHorizontal: CarbonIconNextType
    export const PanVertical: CarbonIconNextType
    export const PanelExpansion: CarbonIconNextType
    export const Paragraph: CarbonIconNextType
    export const Parameter: CarbonIconNextType
    export const ParentChild: CarbonIconNextType
    export const PartlyCloudy: CarbonIconNextType
    export const PartlyCloudyNight: CarbonIconNextType
    export const Partnership: CarbonIconNextType
    export const PassengerDrinks: CarbonIconNextType
    export const PassengerPlus: CarbonIconNextType
    export const Password: CarbonIconNextType
    export const Paste: CarbonIconNextType
    export const Pause: CarbonIconNextType
    export const PauseFilled: CarbonIconNextType
    export const PauseFuture: CarbonIconNextType
    export const PauseOutline: CarbonIconNextType
    export const PauseOutlineFilled: CarbonIconNextType
    export const PausePast: CarbonIconNextType
    export const PcnENode: CarbonIconNextType
    export const PcnMilitary: CarbonIconNextType
    export const PcnPNode: CarbonIconNextType
    export const PcnZNode: CarbonIconNextType
    export const Pdf: CarbonIconNextType
    export const PdfReference: CarbonIconNextType
    export const Pedestrian: CarbonIconNextType
    export const PedestrianChild: CarbonIconNextType
    export const PedestrianFamily: CarbonIconNextType
    export const Pen: CarbonIconNextType
    export const PenFountain: CarbonIconNextType
    export const Pending: CarbonIconNextType
    export const PendingFilled: CarbonIconNextType
    export const Percentage: CarbonIconNextType
    export const PercentageFilled: CarbonIconNextType
    export const Person: CarbonIconNextType
    export const PersonFavorite: CarbonIconNextType
    export const Pest: CarbonIconNextType
    export const Phone: CarbonIconNextType
    export const PhoneApplication: CarbonIconNextType
    export const PhoneBlock: CarbonIconNextType
    export const PhoneBlockFilled: CarbonIconNextType
    export const PhoneFilled: CarbonIconNextType
    export const PhoneIncoming: CarbonIconNextType
    export const PhoneIncomingFilled: CarbonIconNextType
    export const PhoneIp: CarbonIconNextType
    export const PhoneOff: CarbonIconNextType
    export const PhoneOffFilled: CarbonIconNextType
    export const PhoneOutgoing: CarbonIconNextType
    export const PhoneOutgoingFilled: CarbonIconNextType
    export const PhoneSettings: CarbonIconNextType
    export const PhoneVoice: CarbonIconNextType
    export const PhoneVoiceFilled: CarbonIconNextType
    export const PhraseSentiment: CarbonIconNextType
    export const PicnicArea: CarbonIconNextType
    export const PiggyBank: CarbonIconNextType
    export const PiggyBankSlot: CarbonIconNextType
    export const Pills: CarbonIconNextType
    export const PillsAdd: CarbonIconNextType
    export const PillsSubtract: CarbonIconNextType
    export const Pin: CarbonIconNextType
    export const PinFilled: CarbonIconNextType
    export const Plane: CarbonIconNextType
    export const PlanePrivate: CarbonIconNextType
    export const PlaneSea: CarbonIconNextType
    export const Play: CarbonIconNextType
    export const PlayFilled: CarbonIconNextType
    export const PlayFilledAlt: CarbonIconNextType
    export const PlayOutline: CarbonIconNextType
    export const PlayOutlineFilled: CarbonIconNextType
    export const Playlist: CarbonIconNextType
    export const Plug: CarbonIconNextType
    export const PlugFilled: CarbonIconNextType
    export const Png: CarbonIconNextType
    export const PointOfPresence: CarbonIconNextType
    export const Police: CarbonIconNextType
    export const Policy: CarbonIconNextType
    export const Popup: CarbonIconNextType
    export const Portfolio: CarbonIconNextType
    export const Power: CarbonIconNextType
    export const Ppt: CarbonIconNextType
    export const PresentationFile: CarbonIconNextType
    export const Pressure: CarbonIconNextType
    export const PressureFilled: CarbonIconNextType
    export const PreviousFilled: CarbonIconNextType
    export const PreviousOutline: CarbonIconNextType
    export const Printer: CarbonIconNextType
    export const Product: CarbonIconNextType
    export const ProgressBar: CarbonIconNextType
    export const ProgressBarRound: CarbonIconNextType
    export const PropertyRelationship: CarbonIconNextType
    export const Purchase: CarbonIconNextType
    export const QBarrier: CarbonIconNextType
    export const QBlochSphere: CarbonIconNextType
    export const QCU1: CarbonIconNextType
    export const QCU3: CarbonIconNextType
    export const QCY: CarbonIconNextType
    export const QCZ: CarbonIconNextType
    export const QCcX: CarbonIconNextType
    export const QCircuitComposer: CarbonIconNextType
    export const QComposerEdit: CarbonIconNextType
    export const QH: CarbonIconNextType
    export const QHintonPlot: CarbonIconNextType
    export const QID: CarbonIconNextType
    export const QMatrix: CarbonIconNextType
    export const QOperation: CarbonIconNextType
    export const QOperationGauge: CarbonIconNextType
    export const QOperationIf: CarbonIconNextType
    export const QS: CarbonIconNextType
    export const QSAlt: CarbonIconNextType
    export const QT: CarbonIconNextType
    export const QTAlt: CarbonIconNextType
    export const QU1: CarbonIconNextType
    export const QU2: CarbonIconNextType
    export const QU3: CarbonIconNextType
    export const QX: CarbonIconNextType
    export const QY: CarbonIconNextType
    export const QZ: CarbonIconNextType
    export const QqPlot: CarbonIconNextType
    export const QrCode: CarbonIconNextType
    export const QuadrantPlot: CarbonIconNextType
    export const Query: CarbonIconNextType
    export const QueryQueue: CarbonIconNextType
    export const Queued: CarbonIconNextType
    export const Quotes: CarbonIconNextType
    export const Radar: CarbonIconNextType
    export const RadarEnhanced: CarbonIconNextType
    export const RadarWeather: CarbonIconNextType
    export const Radio: CarbonIconNextType
    export const RadioButton: CarbonIconNextType
    export const RadioButtonChecked: CarbonIconNextType
    export const RadioCombat: CarbonIconNextType
    export const RadioPushToTalk: CarbonIconNextType
    export const Rain: CarbonIconNextType
    export const RainDrizzle: CarbonIconNextType
    export const RainDrop: CarbonIconNextType
    export const RainHeavy: CarbonIconNextType
    export const RainScattered: CarbonIconNextType
    export const RainScatteredNight: CarbonIconNextType
    export const Raw: CarbonIconNextType
    export const Receipt: CarbonIconNextType
    export const RecentlyViewed: CarbonIconNextType
    export const Recommend: CarbonIconNextType
    export const Recording: CarbonIconNextType
    export const RecordingFilled: CarbonIconNextType
    export const RecordingFilledAlt: CarbonIconNextType
    export const Redo: CarbonIconNextType
    export const RefEvapotranspiration: CarbonIconNextType
    export const ReflectHorizontal: CarbonIconNextType
    export const ReflectVertical: CarbonIconNextType
    export const Reminder: CarbonIconNextType
    export const ReminderMedical: CarbonIconNextType
    export const Renew: CarbonIconNextType
    export const Repeat: CarbonIconNextType
    export const RepeatOne: CarbonIconNextType
    export const Replicate: CarbonIconNextType
    export const Reply: CarbonIconNextType
    export const ReplyAll: CarbonIconNextType
    export const Report: CarbonIconNextType
    export const ReportData: CarbonIconNextType
    export const RequestQuote: CarbonIconNextType
    export const Reset: CarbonIconNextType
    export const ResetAlt: CarbonIconNextType
    export const Restart: CarbonIconNextType
    export const Restaurant: CarbonIconNextType
    export const RestaurantFine: CarbonIconNextType
    export const Result: CarbonIconNextType
    export const ResultNew: CarbonIconNextType
    export const ResultOld: CarbonIconNextType
    export const RetryFailed: CarbonIconNextType
    export const Review: CarbonIconNextType
    export const Rewind_10: CarbonIconNextType
    export const Rewind_30: CarbonIconNextType
    export const Rewind_5: CarbonIconNextType
    export const Road: CarbonIconNextType
    export const RoadWeather: CarbonIconNextType
    export const Roadmap: CarbonIconNextType
    export const Rocket: CarbonIconNextType
    export const Rotate: CarbonIconNextType
    export const RotateClockwise: CarbonIconNextType
    export const RotateClockwiseAlt: CarbonIconNextType
    export const RotateClockwiseAltFilled: CarbonIconNextType
    export const RotateClockwiseFilled: CarbonIconNextType
    export const RotateCounterclockwise: CarbonIconNextType
    export const RotateCounterclockwiseAlt: CarbonIconNextType
    export const RotateCounterclockwiseAltFilled: CarbonIconNextType
    export const RotateCounterclockwiseFilled: CarbonIconNextType
    export const Router: CarbonIconNextType
    export const RouterVoice: CarbonIconNextType
    export const RouterWifi: CarbonIconNextType
    export const Row: CarbonIconNextType
    export const RowCollapse: CarbonIconNextType
    export const RowDelete: CarbonIconNextType
    export const RowExpand: CarbonIconNextType
    export const RowInsert: CarbonIconNextType
    export const Rss: CarbonIconNextType
    export const Rule: CarbonIconNextType
    export const RuleCancelled: CarbonIconNextType
    export const RuleDataQuality: CarbonIconNextType
    export const RuleDraft: CarbonIconNextType
    export const RuleFilled: CarbonIconNextType
    export const RuleTest: CarbonIconNextType
    export const Ruler: CarbonIconNextType
    export const RulerAlt: CarbonIconNextType
    export const Run: CarbonIconNextType
    export const SailboatCoastal: CarbonIconNextType
    export const SailboatOffshore: CarbonIconNextType
    export const SankeyDiagram: CarbonIconNextType
    export const SankeyDiagramAlt: CarbonIconNextType
    export const Satellite: CarbonIconNextType
    export const SatelliteRadar: CarbonIconNextType
    export const SatelliteWeather: CarbonIconNextType
    export const Save: CarbonIconNextType
    export const SaveModel: CarbonIconNextType
    export const Scale: CarbonIconNextType
    export const Scales: CarbonIconNextType
    export const ScalesTipped: CarbonIconNextType
    export const Scalpel: CarbonIconNextType
    export const Scan: CarbonIconNextType
    export const ScanAlt: CarbonIconNextType
    export const ScanDisabled: CarbonIconNextType
    export const ScatterMatrix: CarbonIconNextType
    export const Schematics: CarbonIconNextType
    export const ScisControlTower: CarbonIconNextType
    export const ScisTransparentSupply: CarbonIconNextType
    export const Scooter: CarbonIconNextType
    export const ScooterFront: CarbonIconNextType
    export const Screen: CarbonIconNextType
    export const ScreenOff: CarbonIconNextType
    export const Script: CarbonIconNextType
    export const ScriptReference: CarbonIconNextType
    export const Sdk: CarbonIconNextType
    export const Search: CarbonIconNextType
    export const SearchAdvanced: CarbonIconNextType
    export const SearchLocate: CarbonIconNextType
    export const Security: CarbonIconNextType
    export const SecurityServices: CarbonIconNextType
    export const SelectWindow: CarbonIconNextType
    export const Select_01: CarbonIconNextType
    export const Select_02: CarbonIconNextType
    export const Send: CarbonIconNextType
    export const SendAlt: CarbonIconNextType
    export const SendAltFilled: CarbonIconNextType
    export const SendBackward: CarbonIconNextType
    export const SendFilled: CarbonIconNextType
    export const SendToBack: CarbonIconNextType
    export const ServerDns: CarbonIconNextType
    export const ServerProxy: CarbonIconNextType
    export const ServerTime: CarbonIconNextType
    export const ServiceDesk: CarbonIconNextType
    export const ServiceId: CarbonIconNextType
    export const SessionBorderControl: CarbonIconNextType
    export const Settings: CarbonIconNextType
    export const SettingsAdjust: CarbonIconNextType
    export const SettingsCheck: CarbonIconNextType
    export const SettingsServices: CarbonIconNextType
    export const SettingsView: CarbonIconNextType
    export const ShapeExcept: CarbonIconNextType
    export const ShapeExclude: CarbonIconNextType
    export const ShapeIntersect: CarbonIconNextType
    export const ShapeJoin: CarbonIconNextType
    export const ShapeUnite: CarbonIconNextType
    export const Share: CarbonIconNextType
    export const ShareKnowledge: CarbonIconNextType
    export const ShoppingBag: CarbonIconNextType
    export const ShoppingCart: CarbonIconNextType
    export const ShoppingCartArrowDown: CarbonIconNextType
    export const ShoppingCartArrowUp: CarbonIconNextType
    export const ShoppingCartClear: CarbonIconNextType
    export const ShoppingCartError: CarbonIconNextType
    export const ShoppingCartMinus: CarbonIconNextType
    export const ShoppingCartPlus: CarbonIconNextType
    export const ShoppingCatalog: CarbonIconNextType
    export const ShowDataCards: CarbonIconNextType
    export const ShrinkScreen: CarbonIconNextType
    export const ShrinkScreenFilled: CarbonIconNextType
    export const Shuffle: CarbonIconNextType
    export const Shuttle: CarbonIconNextType
    export const Sight: CarbonIconNextType
    export const Sigma: CarbonIconNextType
    export const SignalStrength: CarbonIconNextType
    export const SimCard: CarbonIconNextType
    export const SkillLevel: CarbonIconNextType
    export const SkillLevelAdvanced: CarbonIconNextType
    export const SkillLevelBasic: CarbonIconNextType
    export const SkillLevelIntermediate: CarbonIconNextType
    export const SkipBack: CarbonIconNextType
    export const SkipBackFilled: CarbonIconNextType
    export const SkipBackOutline: CarbonIconNextType
    export const SkipBackOutlineFilled: CarbonIconNextType
    export const SkipBackOutlineSolid: CarbonIconNextType
    export const SkipBackSolidFilled: CarbonIconNextType
    export const SkipForward: CarbonIconNextType
    export const SkipForwardFilled: CarbonIconNextType
    export const SkipForwardOutline: CarbonIconNextType
    export const SkipForwardOutlineFilled: CarbonIconNextType
    export const SkipForwardOutlineSolid: CarbonIconNextType
    export const SkipForwardSolidFilled: CarbonIconNextType
    export const Sleet: CarbonIconNextType
    export const Slisor: CarbonIconNextType
    export const Smell: CarbonIconNextType
    export const Smoke: CarbonIconNextType
    export const Snooze: CarbonIconNextType
    export const Snow: CarbonIconNextType
    export const SnowBlizzard: CarbonIconNextType
    export const SnowDensity: CarbonIconNextType
    export const SnowHeavy: CarbonIconNextType
    export const SnowScattered: CarbonIconNextType
    export const SnowScatteredNight: CarbonIconNextType
    export const Snowflake: CarbonIconNextType
    export const Soccer: CarbonIconNextType
    export const SoftwareResource: CarbonIconNextType
    export const SoftwareResourceCluster: CarbonIconNextType
    export const SoftwareResourceResource: CarbonIconNextType
    export const SoilMoisture: CarbonIconNextType
    export const SoilMoistureField: CarbonIconNextType
    export const SoilMoistureGlobal: CarbonIconNextType
    export const SoilTemperature: CarbonIconNextType
    export const SoilTemperatureField: CarbonIconNextType
    export const SoilTemperatureGlobal: CarbonIconNextType
    export const SolarPanel: CarbonIconNextType
    export const SortAscending: CarbonIconNextType
    export const SortDescending: CarbonIconNextType
    export const SortRemove: CarbonIconNextType
    export const SpellCheck: CarbonIconNextType
    export const Split: CarbonIconNextType
    export const SplitScreen: CarbonIconNextType
    export const SprayPaint: CarbonIconNextType
    export const Sprout: CarbonIconNextType
    export const Sql: CarbonIconNextType
    export const SquareFill: CarbonIconNextType
    export const StackLimitation: CarbonIconNextType
    export const Stamp: CarbonIconNextType
    export const Star: CarbonIconNextType
    export const StarFilled: CarbonIconNextType
    export const StarHalf: CarbonIconNextType
    export const StarReview: CarbonIconNextType
    export const StayInside: CarbonIconNextType
    export const StemLeafPlot: CarbonIconNextType
    export const Stethoscope: CarbonIconNextType
    export const Stop: CarbonIconNextType
    export const StopFilled: CarbonIconNextType
    export const StopFilledAlt: CarbonIconNextType
    export const StopOutline: CarbonIconNextType
    export const StopOutlineFilled: CarbonIconNextType
    export const StopSign: CarbonIconNextType
    export const StopSignFilled: CarbonIconNextType
    export const StoragePool: CarbonIconNextType
    export const StorageRequest: CarbonIconNextType
    export const Store: CarbonIconNextType
    export const StormTracker: CarbonIconNextType
    export const Strawberry: CarbonIconNextType
    export const StringInteger: CarbonIconNextType
    export const StringText: CarbonIconNextType
    export const Subflow: CarbonIconNextType
    export const SubflowLocal: CarbonIconNextType
    export const SubnetAclRules: CarbonIconNextType
    export const Subtract: CarbonIconNextType
    export const SubtractAlt: CarbonIconNextType
    export const SummaryKpi: CarbonIconNextType
    export const Sun: CarbonIconNextType
    export const Sunrise: CarbonIconNextType
    export const Sunset: CarbonIconNextType
    export const Svg: CarbonIconNextType
    export const Swim: CarbonIconNextType
    export const SwitchLayer_2: CarbonIconNextType
    export const SwitchLayer_3: CarbonIconNextType
    export const Switcher: CarbonIconNextType
    export const SysProvision: CarbonIconNextType
    export const Table: CarbonIconNextType
    export const TableAlias: CarbonIconNextType
    export const TableBuilt: CarbonIconNextType
    export const TableOfContents: CarbonIconNextType
    export const TableShortcut: CarbonIconNextType
    export const TableSplit: CarbonIconNextType
    export const Tablet: CarbonIconNextType
    export const TabletLandscape: CarbonIconNextType
    export const Tag: CarbonIconNextType
    export const TagEdit: CarbonIconNextType
    export const TagExport: CarbonIconNextType
    export const TagGroup: CarbonIconNextType
    export const TagImport: CarbonIconNextType
    export const TagNone: CarbonIconNextType
    export const Tank: CarbonIconNextType
    export const Task: CarbonIconNextType
    export const TaskAdd: CarbonIconNextType
    export const TaskApproved: CarbonIconNextType
    export const TaskAssetView: CarbonIconNextType
    export const TaskComplete: CarbonIconNextType
    export const TaskLocation: CarbonIconNextType
    export const TaskRemove: CarbonIconNextType
    export const TaskSettings: CarbonIconNextType
    export const TaskStar: CarbonIconNextType
    export const TaskTools: CarbonIconNextType
    export const TaskView: CarbonIconNextType
    export const Taste: CarbonIconNextType
    export const Taxi: CarbonIconNextType
    export const Temperature: CarbonIconNextType
    export const TemperatureCelsius: CarbonIconNextType
    export const TemperatureCelsiusAlt: CarbonIconNextType
    export const TemperatureFahrenheit: CarbonIconNextType
    export const TemperatureFahrenheitAlt: CarbonIconNextType
    export const TemperatureFeelsLike: CarbonIconNextType
    export const TemperatureFrigid: CarbonIconNextType
    export const TemperatureHot: CarbonIconNextType
    export const TemperatureInversion: CarbonIconNextType
    export const TemperatureMax: CarbonIconNextType
    export const TemperatureMin: CarbonIconNextType
    export const TemperatureWater: CarbonIconNextType
    export const Template: CarbonIconNextType
    export const Tennis: CarbonIconNextType
    export const TennisBall: CarbonIconNextType
    export const Term: CarbonIconNextType
    export const Terminal: CarbonIconNextType
    export const Terminal_3270: CarbonIconNextType
    export const TextAlignCenter: CarbonIconNextType
    export const TextAlignJustify: CarbonIconNextType
    export const TextAlignLeft: CarbonIconNextType
    export const TextAlignMixed: CarbonIconNextType
    export const TextAlignRight: CarbonIconNextType
    export const TextAllCaps: CarbonIconNextType
    export const TextBold: CarbonIconNextType
    export const TextClearFormat: CarbonIconNextType
    export const TextColor: CarbonIconNextType
    export const TextCreation: CarbonIconNextType
    export const TextFill: CarbonIconNextType
    export const TextFont: CarbonIconNextType
    export const TextFootnote: CarbonIconNextType
    export const TextHighlight: CarbonIconNextType
    export const TextIndent: CarbonIconNextType
    export const TextIndentLess: CarbonIconNextType
    export const TextIndentMore: CarbonIconNextType
    export const TextItalic: CarbonIconNextType
    export const TextKerning: CarbonIconNextType
    export const TextLeading: CarbonIconNextType
    export const TextLineSpacing: CarbonIconNextType
    export const TextLink: CarbonIconNextType
    export const TextLinkAnalysis: CarbonIconNextType
    export const TextMining: CarbonIconNextType
    export const TextMiningApplier: CarbonIconNextType
    export const TextNewLine: CarbonIconNextType
    export const TextScale: CarbonIconNextType
    export const TextSelection: CarbonIconNextType
    export const TextSmallCaps: CarbonIconNextType
    export const TextStrikethrough: CarbonIconNextType
    export const TextSubscript: CarbonIconNextType
    export const TextSuperscript: CarbonIconNextType
    export const TextTracking: CarbonIconNextType
    export const TextUnderline: CarbonIconNextType
    export const TextVerticalAlignment: CarbonIconNextType
    export const TextWrap: CarbonIconNextType
    export const Theater: CarbonIconNextType
    export const ThisSideUp: CarbonIconNextType
    export const Thumbnail_1: CarbonIconNextType
    export const Thumbnail_2: CarbonIconNextType
    export const ThumbsDown: CarbonIconNextType
    export const ThumbsDownFilled: CarbonIconNextType
    export const ThumbsUp: CarbonIconNextType
    export const ThumbsUpFilled: CarbonIconNextType
    export const Thunderstorm: CarbonIconNextType
    export const ThunderstormScattered: CarbonIconNextType
    export const ThunderstormScatteredNight: CarbonIconNextType
    export const ThunderstormSevere: CarbonIconNextType
    export const ThunderstormStrong: CarbonIconNextType
    export const Ticket: CarbonIconNextType
    export const Tides: CarbonIconNextType
    export const Tif: CarbonIconNextType
    export const Time: CarbonIconNextType
    export const TimePlot: CarbonIconNextType
    export const Timer: CarbonIconNextType
    export const ToolBox: CarbonIconNextType
    export const ToolKit: CarbonIconNextType
    export const Tools: CarbonIconNextType
    export const ToolsAlt: CarbonIconNextType
    export const Tornado: CarbonIconNextType
    export const TornadoWarning: CarbonIconNextType
    export const TouchInteraction: CarbonIconNextType
    export const Touch_1: CarbonIconNextType
    export const Touch_1Down: CarbonIconNextType
    export const Touch_1DownFilled: CarbonIconNextType
    export const Touch_1Filled: CarbonIconNextType
    export const Touch_2: CarbonIconNextType
    export const Touch_2Filled: CarbonIconNextType
    export const TrafficCone: CarbonIconNextType
    export const TrafficEvent: CarbonIconNextType
    export const TrafficFlow: CarbonIconNextType
    export const TrafficFlowIncident: CarbonIconNextType
    export const TrafficIncident: CarbonIconNextType
    export const TrafficWeatherIncident: CarbonIconNextType
    export const Train: CarbonIconNextType
    export const TrainHeart: CarbonIconNextType
    export const TrainProfile: CarbonIconNextType
    export const TrainSpeed: CarbonIconNextType
    export const TrainTicket: CarbonIconNextType
    export const TrainTime: CarbonIconNextType
    export const Tram: CarbonIconNextType
    export const Transgender: CarbonIconNextType
    export const Translate: CarbonIconNextType
    export const TransmissionLte: CarbonIconNextType
    export const Transpose: CarbonIconNextType
    export const TrashCan: CarbonIconNextType
    export const Tree: CarbonIconNextType
    export const TreeFallRisk: CarbonIconNextType
    export const TreeView: CarbonIconNextType
    export const TreeViewAlt: CarbonIconNextType
    export const Trophy: CarbonIconNextType
    export const TrophyFilled: CarbonIconNextType
    export const TropicalStorm: CarbonIconNextType
    export const TropicalStormModelTracks: CarbonIconNextType
    export const TropicalStormTracks: CarbonIconNextType
    export const TropicalWarning: CarbonIconNextType
    export const Tsunami: CarbonIconNextType
    export const Tsv: CarbonIconNextType
    export const TwoFactorAuthentication: CarbonIconNextType
    export const TwoPersonLift: CarbonIconNextType
    export const Txt: CarbonIconNextType
    export const TxtReference: CarbonIconNextType
    export const TypePattern: CarbonIconNextType
    export const Types: CarbonIconNextType
    export const Umbrella: CarbonIconNextType
    export const Undefined: CarbonIconNextType
    export const UndefinedFilled: CarbonIconNextType
    export const Undo: CarbonIconNextType
    export const UngroupObjects: CarbonIconNextType
    export const Unknown: CarbonIconNextType
    export const UnknownFilled: CarbonIconNextType
    export const Unlink: CarbonIconNextType
    export const Unlocked: CarbonIconNextType
    export const UpToTop: CarbonIconNextType
    export const UpdateNow: CarbonIconNextType
    export const Upgrade: CarbonIconNextType
    export const Upload: CarbonIconNextType
    export const Usb: CarbonIconNextType
    export const User: CarbonIconNextType
    export const UserAccess: CarbonIconNextType
    export const UserActivity: CarbonIconNextType
    export const UserAdmin: CarbonIconNextType
    export const UserAvatar: CarbonIconNextType
    export const UserAvatarFilled: CarbonIconNextType
    export const UserAvatarFilledAlt: CarbonIconNextType
    export const UserCertification: CarbonIconNextType
    export const UserData: CarbonIconNextType
    export const UserFavorite: CarbonIconNextType
    export const UserFavoriteAlt: CarbonIconNextType
    export const UserFavoriteAltFilled: CarbonIconNextType
    export const UserFilled: CarbonIconNextType
    export const UserFollow: CarbonIconNextType
    export const UserIdentification: CarbonIconNextType
    export const UserMilitary: CarbonIconNextType
    export const UserMultiple: CarbonIconNextType
    export const UserOnline: CarbonIconNextType
    export const UserProfile: CarbonIconNextType
    export const UserProfileAlt: CarbonIconNextType
    export const UserRole: CarbonIconNextType
    export const UserServiceDesk: CarbonIconNextType
    export const UserSettings: CarbonIconNextType
    export const UserSimulation: CarbonIconNextType
    export const UserSpeaker: CarbonIconNextType
    export const UserXRay: CarbonIconNextType
    export const UvIndex: CarbonIconNextType
    export const UvIndexAlt: CarbonIconNextType
    export const UvIndexFilled: CarbonIconNextType
    export const ValueVariable: CarbonIconNextType
    export const Van: CarbonIconNextType
    export const VegetationAsset: CarbonIconNextType
    export const VehicleApi: CarbonIconNextType
    export const VehicleConnected: CarbonIconNextType
    export const VehicleInsights: CarbonIconNextType
    export const VehicleServices: CarbonIconNextType
    export const Version: CarbonIconNextType
    export const VerticalView: CarbonIconNextType
    export const Video: CarbonIconNextType
    export const VideoAdd: CarbonIconNextType
    export const VideoChat: CarbonIconNextType
    export const VideoFilled: CarbonIconNextType
    export const VideoOff: CarbonIconNextType
    export const VideoOffFilled: CarbonIconNextType
    export const View: CarbonIconNextType
    export const ViewFilled: CarbonIconNextType
    export const ViewMode_1: CarbonIconNextType
    export const ViewMode_2: CarbonIconNextType
    export const ViewNext: CarbonIconNextType
    export const ViewOff: CarbonIconNextType
    export const ViewOffFilled: CarbonIconNextType
    export const VirtualColumn: CarbonIconNextType
    export const VirtualColumnKey: CarbonIconNextType
    export const VirtualDesktop: CarbonIconNextType
    export const VirtualMachine: CarbonIconNextType
    export const VirtualPrivateCloud: CarbonIconNextType
    export const VirtualPrivateCloudAlt: CarbonIconNextType
    export const VisualRecognition: CarbonIconNextType
    export const Vlan: CarbonIconNextType
    export const VlanIbm: CarbonIconNextType
    export const VmdkDisk: CarbonIconNextType
    export const VoiceActivate: CarbonIconNextType
    export const Voicemail: CarbonIconNextType
    export const VolumeBlockStorage: CarbonIconNextType
    export const VolumeDown: CarbonIconNextType
    export const VolumeDownAlt: CarbonIconNextType
    export const VolumeDownFilled: CarbonIconNextType
    export const VolumeDownFilledAlt: CarbonIconNextType
    export const VolumeFileStorage: CarbonIconNextType
    export const VolumeMute: CarbonIconNextType
    export const VolumeMuteFilled: CarbonIconNextType
    export const VolumeObjectStorage: CarbonIconNextType
    export const VolumeUp: CarbonIconNextType
    export const VolumeUpAlt: CarbonIconNextType
    export const VolumeUpFilled: CarbonIconNextType
    export const VolumeUpFilledAlt: CarbonIconNextType
    export const Vpn: CarbonIconNextType
    export const VpnConnection: CarbonIconNextType
    export const VpnPolicy: CarbonIconNextType
    export const Wallet: CarbonIconNextType
    export const Warning: CarbonIconNextType
    export const WarningAlt: CarbonIconNextType
    export const WarningAltFilled: CarbonIconNextType
    export const WarningAltInverted: CarbonIconNextType
    export const WarningAltInvertedFilled: CarbonIconNextType
    export const WarningFilled: CarbonIconNextType
    export const WarningHex: CarbonIconNextType
    export const WarningHexFilled: CarbonIconNextType
    export const WarningOther: CarbonIconNextType
    export const WarningSquare: CarbonIconNextType
    export const WarningSquareFilled: CarbonIconNextType
    export const Watch: CarbonIconNextType
    export const Watson: CarbonIconNextType
    export const WatsonHealth3DCursor: CarbonIconNextType
    export const WatsonHealth3DCursorAlt: CarbonIconNextType
    export const WatsonHealth3DCurveAutoColon: CarbonIconNextType
    export const WatsonHealth3DCurveAutoVessels: CarbonIconNextType
    export const WatsonHealth3DCurveManual: CarbonIconNextType
    export const WatsonHealth3DICa: CarbonIconNextType
    export const WatsonHealth3DMprToggle: CarbonIconNextType
    export const WatsonHealth3DPrintMesh: CarbonIconNextType
    export const WatsonHealth3DSoftware: CarbonIconNextType
    export const WatsonHealth3rdPartyConnected: CarbonIconNextType
    export const WatsonHealthAiResults: CarbonIconNextType
    export const WatsonHealthAiResultsHigh: CarbonIconNextType
    export const WatsonHealthAiResultsLow: CarbonIconNextType
    export const WatsonHealthAiResultsMedium: CarbonIconNextType
    export const WatsonHealthAiResultsUrgent: CarbonIconNextType
    export const WatsonHealthAiResultsVeryHigh: CarbonIconNextType
    export const WatsonHealthAiStatus: CarbonIconNextType
    export const WatsonHealthAiStatusComplete: CarbonIconNextType
    export const WatsonHealthAiStatusFailed: CarbonIconNextType
    export const WatsonHealthAiStatusInProgress: CarbonIconNextType
    export const WatsonHealthAiStatusQueued: CarbonIconNextType
    export const WatsonHealthAiStatusRejected: CarbonIconNextType
    export const WatsonHealthAngle: CarbonIconNextType
    export const WatsonHealthAnnotationVisibility: CarbonIconNextType
    export const WatsonHealthArrowAnnotation: CarbonIconNextType
    export const WatsonHealthAutoScroll: CarbonIconNextType
    export const WatsonHealthBrushFreehand: CarbonIconNextType
    export const WatsonHealthBrushPolygon: CarbonIconNextType
    export const WatsonHealthCdArchive: CarbonIconNextType
    export const WatsonHealthCdCreateArchive: CarbonIconNextType
    export const WatsonHealthCdCreateExchange: CarbonIconNextType
    export const WatsonHealthCircleMeasurement: CarbonIconNextType
    export const WatsonHealthCobbAngle: CarbonIconNextType
    export const WatsonHealthContourDraw: CarbonIconNextType
    export const WatsonHealthContourEdit: CarbonIconNextType
    export const WatsonHealthContourFinding: CarbonIconNextType
    export const WatsonHealthCrossReference: CarbonIconNextType
    export const WatsonHealthCutInHalf: CarbonIconNextType
    export const WatsonHealthDenominate: CarbonIconNextType
    export const WatsonHealthDicomOverlay: CarbonIconNextType
    export const WatsonHealthDicom_6000: CarbonIconNextType
    export const WatsonHealthDna: CarbonIconNextType
    export const WatsonHealthDownloadStudy: CarbonIconNextType
    export const WatsonHealthEdgeEnhancement: CarbonIconNextType
    export const WatsonHealthEdgeEnhancement_01: CarbonIconNextType
    export const WatsonHealthEdgeEnhancement_02: CarbonIconNextType
    export const WatsonHealthEdgeEnhancement_03: CarbonIconNextType
    export const WatsonHealthErase_3D: CarbonIconNextType
    export const WatsonHealthFusionBlender: CarbonIconNextType
    export const WatsonHealthHangingProtocol: CarbonIconNextType
    export const WatsonHealthHl7Attributes: CarbonIconNextType
    export const WatsonHealthHoleFilling: CarbonIconNextType
    export const WatsonHealthHoleFillingCursor: CarbonIconNextType
    export const WatsonHealthICa_2D: CarbonIconNextType
    export const WatsonHealthInteractiveSegmentationCursor: CarbonIconNextType
    export const WatsonHealthLaunchStudy_1: CarbonIconNextType
    export const WatsonHealthLaunchStudy_2: CarbonIconNextType
    export const WatsonHealthLaunchStudy_3: CarbonIconNextType
    export const WatsonHealthMagnify: CarbonIconNextType
    export const WatsonHealthMammogram: CarbonIconNextType
    export const WatsonHealthNominate: CarbonIconNextType
    export const WatsonHealthPageScroll: CarbonIconNextType
    export const WatsonHealthPetImageB: CarbonIconNextType
    export const WatsonHealthPetImageO: CarbonIconNextType
    export const WatsonHealthPointerText: CarbonIconNextType
    export const WatsonHealthQcLaunch: CarbonIconNextType
    export const WatsonHealthRegionAnalysisArea: CarbonIconNextType
    export const WatsonHealthRegionAnalysisVolume: CarbonIconNextType
    export const WatsonHealthRegistration: CarbonIconNextType
    export const WatsonHealthRotate_180: CarbonIconNextType
    export const WatsonHealthRotate_360: CarbonIconNextType
    export const WatsonHealthSaveAnnotation: CarbonIconNextType
    export const WatsonHealthSaveImage: CarbonIconNextType
    export const WatsonHealthSaveSeries: CarbonIconNextType
    export const WatsonHealthScalpelCursor: CarbonIconNextType
    export const WatsonHealthScalpelLasso: CarbonIconNextType
    export const WatsonHealthScalpelSelect: CarbonIconNextType
    export const WatsonHealthSmoothing: CarbonIconNextType
    export const WatsonHealthSmoothingCursor: CarbonIconNextType
    export const WatsonHealthSpineLabel: CarbonIconNextType
    export const WatsonHealthSplitDiscard: CarbonIconNextType
    export const WatsonHealthStackedMove: CarbonIconNextType
    export const WatsonHealthStackedScrolling_1: CarbonIconNextType
    export const WatsonHealthStackedScrolling_2: CarbonIconNextType
    export const WatsonHealthStatusAcknowledge: CarbonIconNextType
    export const WatsonHealthStatusChange: CarbonIconNextType
    export const WatsonHealthStatusPartialFail: CarbonIconNextType
    export const WatsonHealthStatusResolved: CarbonIconNextType
    export const WatsonHealthStressBreathEditor: CarbonIconNextType
    export const WatsonHealthStudyNext: CarbonIconNextType
    export const WatsonHealthStudyPrevious: CarbonIconNextType
    export const WatsonHealthStudyRead: CarbonIconNextType
    export const WatsonHealthStudySkip: CarbonIconNextType
    export const WatsonHealthStudyTransfer: CarbonIconNextType
    export const WatsonHealthStudyUnread: CarbonIconNextType
    export const WatsonHealthStudyView: CarbonIconNextType
    export const WatsonHealthSubVolume: CarbonIconNextType
    export const WatsonHealthTextAnnotationToggle: CarbonIconNextType
    export const WatsonHealthThreshold: CarbonIconNextType
    export const WatsonHealthThumbnailPreview: CarbonIconNextType
    export const WatsonHealthWindowAuto: CarbonIconNextType
    export const WatsonHealthWindowBase: CarbonIconNextType
    export const WatsonHealthWindowBlackSaturation: CarbonIconNextType
    export const WatsonHealthWindowOverlay: CarbonIconNextType
    export const WatsonHealthWindowPreset: CarbonIconNextType
    export const WatsonHealthZoomPan: CarbonIconNextType
    export const WatsonMachineLearning: CarbonIconNextType
    export const WaveDirection: CarbonIconNextType
    export const WaveHeight: CarbonIconNextType
    export const WavePeriod: CarbonIconNextType
    export const WeatherFrontCold: CarbonIconNextType
    export const WeatherFrontStationary: CarbonIconNextType
    export const WeatherFrontWarm: CarbonIconNextType
    export const WeatherStation: CarbonIconNextType
    export const Webhook: CarbonIconNextType
    export const Websheet: CarbonIconNextType
    export const Wheat: CarbonIconNextType
    export const Wifi: CarbonIconNextType
    export const WifiBridge: CarbonIconNextType
    export const WifiBridgeAlt: CarbonIconNextType
    export const WifiController: CarbonIconNextType
    export const WifiNotSecure: CarbonIconNextType
    export const WifiOff: CarbonIconNextType
    export const WifiSecure: CarbonIconNextType
    export const Wikis: CarbonIconNextType
    export const WindGusts: CarbonIconNextType
    export const WindPower: CarbonIconNextType
    export const WindStream: CarbonIconNextType
    export const Windy: CarbonIconNextType
    export const WindyDust: CarbonIconNextType
    export const WindySnow: CarbonIconNextType
    export const WindyStrong: CarbonIconNextType
    export const WinterWarning: CarbonIconNextType
    export const WintryMix: CarbonIconNextType
    export const WirelessCheckout: CarbonIconNextType
    export const Wmv: CarbonIconNextType
    export const WordCloud: CarbonIconNextType
    export const WorkflowAutomation: CarbonIconNextType
    export const Workspace: CarbonIconNextType
    export const WorkspaceImport: CarbonIconNextType
    export const Worship: CarbonIconNextType
    export const WorshipChristian: CarbonIconNextType
    export const WorshipJewish: CarbonIconNextType
    export const WorshipMuslim: CarbonIconNextType
    export const XAxis: CarbonIconNextType
    export const Xls: CarbonIconNextType
    export const Xml: CarbonIconNextType
    export const YAxis: CarbonIconNextType
    export const ZAxis: CarbonIconNextType
    export const Zip: CarbonIconNextType
    export const ZipReference: CarbonIconNextType
    export const ZoomArea: CarbonIconNextType
    export const ZoomFit: CarbonIconNextType
    export const ZoomIn: CarbonIconNextType
    export const ZoomInArea: CarbonIconNextType
    export const ZoomOut: CarbonIconNextType
    export const ZoomOutArea: CarbonIconNextType
    export const ZoomReset: CarbonIconNextType
    export const _4K: CarbonIconNextType
    export const _4KFilled: CarbonIconNextType
}
